In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from colour import XYZ_to_RGB, RGB_to_XYZ
from colour.models import RGB_COLOURSPACE_sRGB
from colour.models.rgb import RGB_COLOURSPACES, RGB_to_XYZ

from colour_lib.utils import *

# CCTFexps

In [5]:
from colour.utilities import CanonicalMapping
from colour.models.rgb import transfer_functions
from colour.models.rgb.transfer_functions import gamma_function
from functools import partial

In [10]:
CUSTOM_DECODINGS: CanonicalMapping = CanonicalMapping(
    {
        "Gamma 1.0": partial(gamma_function, exponent=[1.0, 1.0, 1.0]),
        "Gamma 1.8": partial(gamma_function, exponent=[1.8, 1.8, 1.8]),
    }
)
transfer_functions.CCTF_DECODINGS.update(CUSTOM_DECODINGS)

In [12]:
transfer_functions.cctf_decoding(value=[2, 2, 2], function="Gamma 1.8")

array([ 3.48220225,  3.48220225,  3.48220225])

In [16]:
deco = transfer_functions.cctf_decoding

In [17]:
deco(value=[2, 2, 2], function="Gamma 1.8")

array([ 3.48220225,  3.48220225,  3.48220225])

In [13]:
CUSTOM_ENCODINGS: CanonicalMapping = CanonicalMapping(
    {
        "Gamma 1.0": partial(
            gamma_function, exponent=[1.0 / 1.0, 1.0 / 1.0, 1.0 / 1.0]
        ),
        "Gamma 1.8": partial(
            gamma_function, exponent=[1.0 / 1.8, 1.0 / 1.8, 1.0 / 1.8]
        ),
    }
)
transfer_functions.CCTF_ENCODINGS.update(CUSTOM_ENCODINGS)

In [15]:
transfer_functions.cctf_encoding(
    value=[3.48220225, 3.48220225, 3.48220225], function="Gamma 1.8"
)

array([ 2.,  2.,  2.])

In [18]:
enco = transfer_functions.cctf_encoding

In [3]:
CCTF = CustomCCTF()
CCTF.apply_CCTF(
    mode="encode", cctf_type="Gamma 1.8", image=[3.48220225, 3.48220225, 3.48220225]
)

array([ 2.,  2.,  2.])

# Download features

In [4]:
global_dir = "/uftp/src/"
rw = RawDataParser(reference_basepath=f"{global_dir}calibration_data/")
SRGB_COLSPACE = RGB_COLOURSPACES["sRGB"]
NTSC_COLSPACE = RGB_COLOURSPACES["NTSC (1987)"]

In [6]:
images = {
    "R1_111": image_read(
        f"{global_dir}palettes/Calib_R1_10_10_10_202402.tif", 3, [1.0, 1.0, 1.0]
    ),
    "Polaris": image_read(
        f"{global_dir}palettes/Calib_Polaris_Scan3.qptiff", 6, [1.8, 1.8, 1.8]
    ),
}
images["R1_111_XYZ"] = RGB_to_XYZ(
    RGB=images["R1_111"], colourspace=RGB_COLOURSPACES["sRGB"]
)

images["Polaris_XYZ"] = RGB_to_XYZ(
    RGB=images["R1_111"], colourspace=RGB_COLOURSPACES["NTSC (1987)"]
)

<tifffile.TiffPage 6 @11318147692> missing data offset tag


In [7]:
from sklearn.ensemble import RandomForestRegressor

reg = RandomForestRegressor(max_depth=2, random_state=0)
reg.fit(np.random.rand(24, 3), np.random.rand(24, 3))
reg.predict(np.random.rand(24, 3))

array([[ 0.56940154,  0.62848042,  0.55641022],
       [ 0.6524309 ,  0.41373774,  0.59928695],
       [ 0.68089407,  0.5962558 ,  0.56948365],
       [ 0.66085797,  0.62014433,  0.5852964 ],
       [ 0.50428036,  0.61228082,  0.57946978],
       [ 0.57089032,  0.33876423,  0.4945139 ],
       [ 0.659932  ,  0.61190162,  0.62503012],
       [ 0.64086033,  0.60351873,  0.59805213],
       [ 0.65453072,  0.61880213,  0.6111183 ],
       [ 0.62597955,  0.41697983,  0.57717588],
       [ 0.62701186,  0.39844651,  0.57983778],
       [ 0.56786149,  0.63239208,  0.57190246],
       [ 0.58402363,  0.32074526,  0.47593254],
       [ 0.69128845,  0.60422514,  0.6179205 ],
       [ 0.61709614,  0.41082251,  0.56598131],
       [ 0.64331075,  0.62621434,  0.5692799 ],
       [ 0.52782462,  0.31990648,  0.4581768 ],
       [ 0.56386045,  0.32358779,  0.49847484],
       [ 0.53878191,  0.32561119,  0.49536935],
       [ 0.6724209 ,  0.60602319,  0.58801689],
       [ 0.4992837 ,  0.30874934,  0.450